version: "3.8"
services:
  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/index.html:/usr/share/nginx/html/index.html
      - ./docker/meta.html:/usr/share/nginx/html/meta.html
      - ./docker/blank.html:/usr/share/nginx/html/blank.html
      - ./docker/heavy.html:/usr/share/nginx/html/heavy.html
